[package]
name = "sd-p2p"
version = "0.1.0"
description = "Rust Peer to Peer Networking Library"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[features]
default = []
serde = []
specta = []

[dependencies]
tokio = { workspace = true, features = [
	"macros",
	"sync",
	"time",
	"io-util",
	"fs",
] }
libp2p = { version = "0.51.3", features = ["tokio", "serde"] }
libp2p-quic = { version = "0.7.0-alpha.3", features = ["tokio"] }
if-watch = { version = "3.0.1", features = ["tokio"] } # Override the features of if-watch which is used by libp2p-quic
mdns-sd = "0.6.1"
thiserror = "1.0.40"
tracing = "0.1.37"
serde = { version = "1.0.163", features = ["derive"] }
rmp-serde = "1.1.1"
specta = { workspace = true }
flume = "0.10.14"
tokio-util = { version = "0.7.8", features = ["compat"] }
arc-swap = "1.6.0"
p384 = { version = "0.13.0", feature = ["ecdh"] }
ed25519-dalek = { version = "1.0.1", features = ["rand"] }
rand_core = { version = "0.5.1", feature = ["getrandom"] }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
